server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anime?&createDatabaseIfNotExists=true
    username: developer
    password: leticia12@
  jpa:
     hibernate:
       ddl-auto: create
       show-sql: true

